package ddd;

import static org.junit.Assert.*;
import org.junit.Test;

import com.esdrasmorais.ddd.repository.MongoContext;
import com.esdrasmorais.ddd.repository.MongoRepository;
import com.esdrasmorais.ddd.repository.interfaces.IClient;
import com.esdrasmorais.ddd.repository.interfaces.IContext;
import com.esdrasmorais.ddd.repository.interfaces.IDb;
import static org.mockito.Mockito.*;

/**
 * This java source file was generated by the Gradle 'init' task.
 */
public class DddTests {
    @Test public void testRepository() {
    	/*assertTrue(
	    "mongo.uri true",
    	    System.getProperty("mongo.uri") != null
    	);*/
  	//IContext context = new MongoContext();
        IContext contextMocked = mock(IContext.class);
	when(contextMocked.getClient()).thenReturn(mock(IClient.class));
 	IClient client = contextMocked.getClient();
	
	IDb dbMocked = mock(IDb.class);
	//when(dbMocked.getDb("Drones")).thenReturn(mock(IDb.class));
	IDb db = client.getDb("Drones");
	
    	UserRepository userRepository = new UserRepository(
    	    contextMocked, client, db
    	);

System.out.println(userRepository);

	assertTrue("Repository is Instanced", userRepository instanceof UserRepository);

        /*assertTrue(
			"should return 'true'", 
			userRepository instanceof MongoRepository<?>
        );*/
        
	//        assertTrue(
	//        	userRepository.findAll().size() >= 0
	//        );
    }
}
