package ddd;

import org.junit.Test;
import static org.junit.Assert.*;
import com.esdrasmorais.ddd.repository.MongoRepository;

/**
 * This java source file was generated by the Gradle 'init' task.
 */
public class DddTests {
    @Test public void testRepository() {
    	assertTrue(
    		System.getProperty("mongo_uri") == System.getProperty("mongo.uri")
    	);
    	
    	UserRepository userRepository = new UserRepository(
    		null, null, null
    	);
        assertTrue(
			"should return 'true'", 
			userRepository instanceof MongoRepository<?>
        );
    }
}
