
import org.junit.Test;
import static org.junit.Assert.*;
import com.esdrasmorais.ddd.repository.MongoRepository;

/**
 * This java source file was generated by the Gradle 'init' task.
 */
public class RepositoryTest {
    @Test public void testRepository() {
    	MongoRepository<User> mongoRepository = new MongoRepository<User>(
    		null, null, null
    	);
        assertTrue(
			"should return 'true'", 
			mongoRepository instanceof MongoRepository<?>
        );
    }
}
